version: '3'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    links:
      - mail
      # - mysql
      - postgres
      #- solr
      #- elasticsearch
      # - redis
      #- memcached
      #- ftp
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - ./:/api/
      # - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025

  #######################################
  # PostgreSQL server
  #######################################
  postgres:
   build:
     context: docker/postgres/
    #dockerfile: Postgres-9.4.Dockerfile
     dockerfile: Postgres-9.5.Dockerfile
   ports:
     - 15432:5432
   volumes:
     - postgres:/var/lib/postgresql/data
   env_file:
     - etc/environment.yml
     - etc/environment.development.yml

  #######################################
  # Redis
  #######################################
  #redis:
  #  build:
  #    context: docker/redis/
  #  volumes:
  #    - redis:/data
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.development.yml

 #######################################
  # Mail
  #######################################
  # Mailhog
  mail:
     image: mailhog/mailhog
   #  ports:
   #    - 8025:8025
     environment:
      - VIRTUAL_HOST=mail.boilerplate.docker
      - VIRTUAL_PORT=8025

  #######################################
  # phpMyAdmin
  #######################################
  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   links:
     - postgres
   environment:
     - PMA_HOSTS=postgres
     - VIRTUAL_HOST=pma.boilerplate.docker
     - VIRTUAL_PORT=80
   volumes:
     - phpmyadmin:/sessions

volumes:
  postgres:
  redis:
  phpmyadmin:
